# Generated by Django 3.2.5 on 2021-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dichvu', '0002_alter_dichvu_tomtat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhomdichvu',
            options={'verbose_name_plural': 'Nhóm Dịch vụ'},
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='hinh',
            field=models.ImageField(blank=True, null=True, upload_to='dichvu/', verbose_name='Hình'),
        ),
    ]
