# Generated by Django 3.2.5 on 2021-10-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dichvu', '0003_auto_20211001_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='nhomdichvu',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, verbose_name='slug'),
        ),
    ]
