# Generated by Django 3.2.5 on 2021-08-27 10:03

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('tomtat', models.CharField(max_length=1000, verbose_name='Tóm tắt')),
                ('noidung', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung')),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Hình')),
                ('ngaynhap', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Nội dung Tin tức',
            },
        ),
    ]
