# Generated by Django 3.2.5 on 2021-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0002_auto_20210831_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintucform',
            name='tomtat',
            field=models.TextField(max_length=1000, verbose_name='Tóm tắt'),
        ),
    ]
