# Generated by Django 3.2.5 on 2021-10-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0004_alter_tintucform_hinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintucform',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='slug'),
        ),
    ]
