# Generated by Django 3.2.5 on 2021-10-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0005_tintucform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintucform',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, verbose_name='slug'),
        ),
    ]
