# Generated by Django 3.2.5 on 2021-08-31 06:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhomSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nhóm sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=500, verbose_name='Tên sản phẩm')),
                ('tomtat', models.TextField(max_length=1000, verbose_name='Tóm tắt')),
                ('noidung', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung')),
                ('hinh', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Hình')),
                ('ngaynhap', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('nhomsanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.nhomsanpham')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết sản phẩm',
            },
        ),
    ]
