# Generated by Django 3.2.5 on 2021-08-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhomsanpham',
            options={'verbose_name_plural': 'Nhóm Sản phẩm'},
        ),
    ]
