# Generated by Django 3.2.5 on 2021-08-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_alter_nhomsanpham_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPhamHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Hình')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'verbose_name_plural': 'Hình sản phẩm',
            },
        ),
    ]
