# Generated by Django 3.2.5 on 2021-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0003_sanphamhinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='sanphamhinh',
            name='hinh',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Thư viện hình'),
        ),
    ]
