# Generated by Django 3.2.5 on 2021-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20210905_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='gia_chinh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá chinh'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='gia_khuyenmai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá khuyến mãi'),
        ),
    ]
