# Generated by Django 3.2.5 on 2021-09-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0005_auto_20210905_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham_Moi_NoiBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kieu', models.SmallIntegerField(choices=[(1, 'Mới'), (2, 'Nổi bật')], max_length=2, verbose_name='Kiểu sản phẩm ')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm mới, nổi bật',
            },
        ),
    ]
