# Generated by Django 3.2.5 on 2021-09-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0006_sanpham_moi_noibat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham_moi_noibat',
            name='nhomsanpham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sanpham.nhomsanpham'),
            preserve_default=False,
        ),
    ]
