# Generated by Django 3.2.5 on 2021-09-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0007_sanpham_moi_noibat_nhomsanpham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham_moi_noibat',
            name='kieu',
            field=models.SmallIntegerField(choices=[(1, 'Mới'), (2, 'Nổi bật')], verbose_name='Kiểu sản phẩm '),
        ),
    ]
