# Generated by Django 3.2.5 on 2021-09-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0008_alter_sanpham_moi_noibat_kieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham_moi_noibat',
            name='nhomsanpham',
        ),
    ]
