# Generated by Django 3.2.5 on 2021-09-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0009_remove_sanpham_moi_noibat_nhomsanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham_moi_noibat',
            name='nhomsanpham',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='sanpham.nhomsanpham'),
        ),
        migrations.AlterField(
            model_name='sanpham_moi_noibat',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham', unique=True),
        ),
    ]
