# Generated by Django 3.2.5 on 2021-09-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0010_auto_20210914_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='gia_chinh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá chinh'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia_khuyenmai',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nhomsanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sanpham.nhomsanpham'),
        ),
        migrations.AlterField(
            model_name='sanpham_moi_noibat',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham'),
        ),
    ]
