# Generated by Django 3.2.5 on 2021-09-15 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0011_auto_20210915_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='nhomsanpham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='sanpham.sanpham'),
        ),
    ]
