# Generated by Django 3.2.5 on 2021-09-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0012_alter_sanpham_nhomsanpham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='nhomsanpham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sanpham.nhomsanpham'),
            preserve_default=False,
        ),
    ]
