# Generated by Django 3.2.5 on 2021-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0013_alter_sanpham_nhomsanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='sp_khuyenmai',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sản phẩm khuyến mãi'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sp_moi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sản phẩm mới'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sp_noibat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sản phẩm nổi bật'),
        ),
        migrations.DeleteModel(
            name='SanPham_Moi_NoiBat',
        ),
    ]
