# Generated by Django 3.2.5 on 2021-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0014_auto_20210916_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='sp_khuyenmai',
            field=models.BooleanField(blank=True, null=True, verbose_name='SP khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sp_moi',
            field=models.BooleanField(blank=True, null=True, verbose_name='SP mới'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sp_noibat',
            field=models.BooleanField(blank=True, null=True, verbose_name='SP nổi bật'),
        ),
    ]
