# Generated by Django 3.2.5 on 2021-10-01 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0016_dathangsanphammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='id_sanpham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='ngaynhap',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập'),
        ),
    ]
