# Generated by Django 3.2.5 on 2021-10-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0017_auto_20211001_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dathangsanphammodel',
            old_name='id_sanpham',
            new_name='sanpham',
        ),
    ]
