# Generated by Django 3.2.5 on 2021-10-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0018_rename_id_sanpham_dathangsanphammodel_sanpham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham'),
        ),
    ]
