# Generated by Django 3.2.5 on 2021-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0020_auto_20211001_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathangsanphammodel',
            name='sanpham',
        ),
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.IntegerField(default=1, verbose_name='Sản phẩm'),
            preserve_default=False,
        ),
    ]
