# Generated by Django 3.2.5 on 2021-10-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0021_auto_20211001_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathangsanphammodel',
            name='sanpham',
        ),
    ]
