# Generated by Django 3.2.5 on 2021-10-01 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0024_remove_dathangsanphammodel_ngaynhap'),
    ]

    operations = [
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='ngaynhap',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập'),
        ),
    ]
