# Generated by Django 3.2.5 on 2021-10-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0025_dathangsanphammodel_ngaynhap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathangsanphammodel',
            name='ngaynhap',
        ),
    ]
