# Generated by Django 3.2.5 on 2021-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0028_alter_dathangsanphammodel_sanpham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathangsanphammodel',
            name='sanpham',
        ),
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.ManyToManyField(to='sanpham.SanPham'),
        ),
    ]
