# Generated by Django 3.2.5 on 2021-10-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0029_auto_20211001_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathangsanphammodel',
            name='sanpham',
        ),
        migrations.AddField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham'),
            preserve_default=False,
        ),
    ]
