# Generated by Django 3.2.5 on 2021-10-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0030_auto_20211001_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='dathangsanphammodel',
            name='soluong',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
    ]
