# Generated by Django 3.2.5 on 2021-10-02 07:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0031_auto_20211002_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathangsanphammodel',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham'),
        ),
        migrations.CreateModel(
            name='NhanXetSanPhamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150, verbose_name='Tên người nhận xét')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('noidung', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ngaynhap', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'verbose_name_plural': 'Thông tin nhận xét',
            },
        ),
    ]
