# Generated by Django 3.2.5 on 2021-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0032_auto_20211002_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathangsanphammodel',
            name='noidung',
            field=models.TextField(default=1, verbose_name='Nội dung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nhanxetsanphammodel',
            name='noidung',
            field=models.TextField(default=2, verbose_name='Nội dung'),
            preserve_default=False,
        ),
    ]
