# Generated by Django 3.2.5 on 2021-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0033_auto_20211002_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanxetsanphammodel',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
    ]
