# Generated by Django 3.2.5 on 2021-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0034_alter_nhanxetsanphammodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanxetsanphammodel',
            name='sosao',
            field=models.IntegerField(default=1, verbose_name='Số sao'),
            preserve_default=False,
        ),
    ]
