# Generated by Django 3.2.5 on 2021-10-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0035_nhanxetsanphammodel_sosao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanxetsanphammodel',
            name='sosao',
        ),
    ]
