# Generated by Django 3.2.5 on 2021-10-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0036_remove_nhanxetsanphammodel_sosao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomsanpham',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, verbose_name='slug'),
        ),
    ]
