# Generated by Django 3.2.5 on 2021-08-27 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name_plural': 'Liên hệ'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
