# Generated by Django 3.2.5 on 2021-08-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210827_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='username',
            field=models.CharField(max_length=25, verbose_name='UserName'),
        ),
    ]
