# Generated by Django 3.2.5 on 2021-09-28 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210831_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150, verbose_name='Tên người liên hệ')),
                ('dienthoai', models.CharField(max_length=50, verbose_name='Điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('noidung', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Thông tin người liên hệ',
            },
        ),
        migrations.RenameModel(
            old_name='ContentcontactForm',
            new_name='ContentcontactModel',
        ),
        migrations.RenameModel(
            old_name='MapcontactForm',
            new_name='MapcontactModel',
        ),
        migrations.DeleteModel(
            name='contactForm',
        ),
    ]
