# Generated by Django 3.2.5 on 2021-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeform',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
    ]
