# Generated by Django 3.2.5 on 2021-08-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeform_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeform',
            options={'verbose_name': 'Trang chủ', 'verbose_name_plural': 'Nội dung Trang chủ'},
        ),
    ]
