# Generated by Django 3.2.5 on 2021-09-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homeform_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeThuVienHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=500, verbose_name='Tiêu đề')),
            ],
            options={
                'verbose_name_plural': 'LiveShow hình trang chủ',
            },
        ),
        migrations.CreateModel(
            name='HomeThuVienHinh_ChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh', models.FileField(blank=True, null=True, upload_to='imagesHome/', verbose_name='Thư viện hình')),
                ('homethuvienhinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homethuvienhinh')),
            ],
            options={
                'verbose_name_plural': 'Hình chi tiết',
            },
        ),
    ]
