# Generated by Django 3.2.5 on 2021-09-17 07:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homethuvienhinh_homethuvienhinh_chitiet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeform',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
