# Generated by Django 3.2.5 on 2021-09-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homeform_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeHotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hotline')),
            ],
            options={
                'verbose_name_plural': 'Hotline',
            },
        ),
    ]
