# Generated by Django 3.2.5 on 2021-09-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cl_bottom',
            options={'verbose_name_plural': 'Nội dung Bottom'},
        ),
    ]
