# Generated by Django 3.2.5 on 2021-10-03 12:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottom', '0002_alter_cl_bottom_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_baohanh_doitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bảo hành & đổi trả',
            },
        ),
        migrations.CreateModel(
            name='cl_chinhsach_banhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chính sách bán hàng',
            },
        ),
        migrations.CreateModel(
            name='cl_chinhsach_giaohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chính sách giao hàng',
            },
        ),
        migrations.CreateModel(
            name='cl_quydinh_thanhtoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quy định & hình thức thanh toán',
            },
        ),
    ]
