# Generated by Django 3.2.5 on 2021-10-04 02:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottom', '0003_cl_baohanh_doitra_cl_chinhsach_banhang_cl_chinhsach_giaohang_cl_quydinh_thanhtoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_huongdanmuahang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hướng dẫn mua hàng',
            },
        ),
        migrations.CreateModel(
            name='cl_quychehoatdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quy chế hoạt động',
            },
        ),
        migrations.CreateModel(
            name='cl_tuyendung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tuyển dụng',
            },
        ),
    ]
